---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grafana-google-sso-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: grafana-client-secret
    creationPolicy: Owner
  data:
  - secretKey: clientSecret
    remoteRef:
      key: grafana-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grafana-google-sso-id
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: grafana-client-id
    creationPolicy: Owner
  data:
  - secretKey: clientID
    remoteRef:
      key: grafana-client-id
