apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: oci-vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.enuwvho4aadzi.abtheljryyg5qwabwtp2laz52j6arki6hpwakhnmjyfcjgfism3achtz3i3q
      region: eu-frankfurt-1
