---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leonhrt/oci-kubernetes
    targetRevision: HEAD
    path: external-secrets
  destination:
    name: oci-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
