---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: external-secrets
  namespace: argocd
spec:
  syncPolicy: 
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: oci-cluster
  template:
    metadata:
      name: "external-secrets-{{cluster}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/leonhrt/oci-kubernetes
        targetRevision: HEAD
        path: "external-secrets/overlays/{{cluster}}"
      destination:
        name: "{{cluster}}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
