---
apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.leonhrt.com
  dex.config: |
    connectors:
    - type: google
      id: google
      name: Google
      config:
        clientID: $argocd-client-secret:clientID
        clientSecret: $argocd-client-secret:clientSecret
        redirectURI: https://argocd.leonhrt.com/api/dex/callback
