---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: argocd-google-sso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: google-client-secret
    creationPolicy: Owner
  data:
  - secretKey: google-client-secret
    remoteRef:
      key: clientSecret
