---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: argocd-google-sso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: google-client-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: clientSecret
    remoteRef:
      key: google-client-secret
