---
apiVersion: v1
kind: Secret
metadata:
  name: repo-k8s-core
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/leonhrt/k8s-core
